chain-id: 1
private-key-encrypted: "OwWrEtDWl7mq79FM-mb4hbrU9uBtffvX3MPuEjcXenWocH-JS4SVYXFr0rm-wYuWHnwrzLYvatKGywShwMVCEZw6f-g2XyDIPdrEzAHCZ8WH_v76kJsVEOGEe8qRvy4z6ai0YGFpzV4iFB8NfZEg5kb9k88"
base-multiplier: 2000
time-labels:
  - name: "Time: <1 Hour"
    weight: 0.125
    value: 3600
    target: "Price: 12.5+ USD"
  - name: "Time: <1 Day"
    weight: 1
    value: 86400
    target: "Price: 100+ USD"
  - name: "Time: <1 Week"
    weight: 2
    value: 604800
    target: "Price: 200+ USD"
  - name: "Time: <2 Weeks"
    weight: 3
    value: 1209600
    target: "Price: 300+ USD"
  - name: "Time: <1 Month"
    weight: 4
    value: 2592000
    target: "Price: 400+ USD"
priority-labels:
  - name: "Priority: 0 (Normal)"
    weight: 1
    target: "Price: 100+ USD"
  - name: "Priority: 1 (Medium)"
    weight: 2
    target: "Price: 200+ USD"
  - name: "Priority: 2 (High)"
    weight: 3
    target: "Price: 300+ USD"
  - name: "Priority: 3 (Urgent)"
    weight: 4
    target: "Price: 400+ USD"
  - name: "Priority: 4 (Emergency)"
    weight: 5
    target: "Price: 500+ USD"
auto-pay-mode: true
analytics-mode: false
incentive-mode: false
max-concurrent-bounties: 2
